spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: 123
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
  h2:
    console:
      enable: true
      path: /h2